name: Docker

on:
  worflow_call:
  
jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Setup Build
      uses: docker/setup-buildx-action@v2.0.0

    - name: Docker Login 
      uses: docker/login-action@v2.0.0 
      with: 
        username: ${{ secrets.USERNAME_DOCKER_HUB }}
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}